/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedCapacitacionesRouteImport } from './routes/_authenticated/capacitaciones'
import { Route as AuthenticatedCasosRouteImport } from './routes/_authenticated/casos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMiperRouteImport } from './routes/_authenticated/miper'
import { Route as AuthenticatedPlanesAccionRouteImport } from './routes/_authenticated/planes-accion'
import { Route as AuthenticatedReportesRouteImport } from './routes/_authenticated/reportes'
import { Route as AuthActualizarClaveRouteImport } from './routes/auth.actualizar-clave'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCapacitacionesRoute =
  AuthenticatedCapacitacionesRouteImport.update({
    id: '/capacitaciones',
    path: '/capacitaciones',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCasosRoute = AuthenticatedCasosRouteImport.update({
  id: '/casos',
  path: '/casos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMiperRoute = AuthenticatedMiperRouteImport.update({
  id: '/miper',
  path: '/miper',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanesAccionRoute =
  AuthenticatedPlanesAccionRouteImport.update({
    id: '/planes-accion',
    path: '/planes-accion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportesRoute = AuthenticatedReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthActualizarClaveRoute = AuthActualizarClaveRouteImport.update({
  id: '/actualizar-clave',
  path: '/actualizar-clave',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/capacitaciones': typeof AuthenticatedCapacitacionesRoute
  '/casos': typeof AuthenticatedCasosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/miper': typeof AuthenticatedMiperRoute
  '/planes-accion': typeof AuthenticatedPlanesAccionRoute
  '/reportes': typeof AuthenticatedReportesRoute
  '/auth/actualizar-clave': typeof AuthActualizarClaveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/capacitaciones': typeof AuthenticatedCapacitacionesRoute
  '/casos': typeof AuthenticatedCasosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/miper': typeof AuthenticatedMiperRoute
  '/planes-accion': typeof AuthenticatedPlanesAccionRoute
  '/reportes': typeof AuthenticatedReportesRoute
  '/auth/actualizar-clave': typeof AuthActualizarClaveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/capacitaciones': typeof AuthenticatedCapacitacionesRoute
  '/_authenticated/casos': typeof AuthenticatedCasosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/miper': typeof AuthenticatedMiperRoute
  '/_authenticated/planes-accion': typeof AuthenticatedPlanesAccionRoute
  '/_authenticated/reportes': typeof AuthenticatedReportesRoute
  '/auth/actualizar-clave': typeof AuthActualizarClaveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/capacitaciones'
    | '/casos'
    | '/dashboard'
    | '/miper'
    | '/planes-accion'
    | '/reportes'
    | '/auth/actualizar-clave'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/capacitaciones'
    | '/casos'
    | '/dashboard'
    | '/miper'
    | '/planes-accion'
    | '/reportes'
    | '/auth/actualizar-clave'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/capacitaciones'
    | '/_authenticated/casos'
    | '/_authenticated/dashboard'
    | '/_authenticated/miper'
    | '/_authenticated/planes-accion'
    | '/_authenticated/reportes'
    | '/auth/actualizar-clave'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/capacitaciones': {
      id: '/_authenticated/capacitaciones'
      path: '/capacitaciones'
      fullPath: '/capacitaciones'
      preLoaderRoute: typeof AuthenticatedCapacitacionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/casos': {
      id: '/_authenticated/casos'
      path: '/casos'
      fullPath: '/casos'
      preLoaderRoute: typeof AuthenticatedCasosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/miper': {
      id: '/_authenticated/miper'
      path: '/miper'
      fullPath: '/miper'
      preLoaderRoute: typeof AuthenticatedMiperRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planes-accion': {
      id: '/_authenticated/planes-accion'
      path: '/planes-accion'
      fullPath: '/planes-accion'
      preLoaderRoute: typeof AuthenticatedPlanesAccionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reportes': {
      id: '/_authenticated/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof AuthenticatedReportesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/actualizar-clave': {
      id: '/auth/actualizar-clave'
      path: '/actualizar-clave'
      fullPath: '/auth/actualizar-clave'
      preLoaderRoute: typeof AuthActualizarClaveRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCapacitacionesRoute: typeof AuthenticatedCapacitacionesRoute
  AuthenticatedCasosRoute: typeof AuthenticatedCasosRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMiperRoute: typeof AuthenticatedMiperRoute
  AuthenticatedPlanesAccionRoute: typeof AuthenticatedPlanesAccionRoute
  AuthenticatedReportesRoute: typeof AuthenticatedReportesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCapacitacionesRoute: AuthenticatedCapacitacionesRoute,
  AuthenticatedCasosRoute: AuthenticatedCasosRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMiperRoute: AuthenticatedMiperRoute,
  AuthenticatedPlanesAccionRoute: AuthenticatedPlanesAccionRoute,
  AuthenticatedReportesRoute: AuthenticatedReportesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthActualizarClaveRoute: typeof AuthActualizarClaveRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthActualizarClaveRoute: AuthActualizarClaveRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
